self.moveUp(2);
self.attack("Door A")
self.moveUp(2)
enemy = self.findNearestEnemy()
self.attack(enemy)
self.attack(enemy)
self.attack(enemy)
self.moveDown(3)
self.moveRight(2)
self.moveUp()
self.moveRight(4)
enemy = self.findNearestEnemy()
self.attack(enemy)
self.attack(enemy)
self.attack(enemy)
enemy = self.findNearestEnemy()
self.attack(enemy)
self.attack(enemy)
self.attack(enemy)
self.moveUp(3)
self.moveRight()
self.moveLeft()
self.moveDown(3)
self.moveLeft(4)
self.moveDown(2)